baseurl: "/"
permalink: pretty
title: "KKEULMIT"
url: "/"

logo:
  mobile: "images/logo/kkeulmitlogo.svg"
  mobile_height: "60px"
  mobile_width: "200px"
  desktop: "images/logo/kkeulmitlogo.svg"
  desktop_height: "60px"
  desktop_width: "200px"

collections:
  services:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
